package forms;

import javax.swing.table.DefaultTableModel;
import model.Item;

import forms.MenuScreen;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import utils.Utils;

public class StockScreen extends javax.swing.JDialog {

    /**
     * Creates new form StockScreen
     */
    public StockScreen(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER); // Centraliza horizontalmente

        tableRegistereds.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistereds = new javax.swing.JTable();
        fieldSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        comboFilter = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();
        labelNumberOfSearchResults = new javax.swing.JLabel();
        buttonSearch1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ESTOQUE DE ITEMS");
        setMaximumSize(new java.awt.Dimension(1360, 625));
        setMinimumSize(new java.awt.Dimension(1360, 625));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(1360, 625));
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 625));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tableRegistereds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableRegistereds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Editora", "Gênero", "Pág. / Faixas", "Autor/Manchete", "Ano", "Tipo", "P. Fornecedor", "M. Lucro", "P. de Venda", "Lucro p/ unidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRegistereds.setRowHeight(30);
        tableRegistereds.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tableRegistereds.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableRegistereds.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableRegistereds.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableRegistereds);
        if (tableRegistereds.getColumnModel().getColumnCount() > 0) {
            tableRegistereds.getColumnModel().getColumn(0).setMinWidth(60);
            tableRegistereds.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableRegistereds.getColumnModel().getColumn(0).setMaxWidth(60);
            tableRegistereds.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableRegistereds.getColumnModel().getColumn(2).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableRegistereds.getColumnModel().getColumn(3).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableRegistereds.getColumnModel().getColumn(4).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableRegistereds.getColumnModel().getColumn(5).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(5).setPreferredWidth(150);
            tableRegistereds.getColumnModel().getColumn(6).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(6).setPreferredWidth(40);
            tableRegistereds.getColumnModel().getColumn(7).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(8).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(9).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(10).setResizable(false);
            tableRegistereds.getColumnModel().getColumn(11).setResizable(false);
        }

        fieldSearch.setMaximumSize(new java.awt.Dimension(350, 35));
        fieldSearch.setMinimumSize(new java.awt.Dimension(350, 35));
        fieldSearch.setPreferredSize(new java.awt.Dimension(350, 35));

        buttonSearch.setBackground(new java.awt.Color(0, 153, 204));
        buttonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setText("BUSCAR");
        buttonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TITULO", "EDITORA", "AUTOR" }));
        comboFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FILTRO:");

        buttonDelete.setBackground(new java.awt.Color(255, 51, 51));
        buttonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("DELETAR");
        buttonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        labelNumberOfSearchResults.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        buttonSearch1.setBackground(new java.awt.Color(0, 153, 204));
        buttonSearch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSearch1.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/reload.png"))); // NOI18N
        buttonSearch1.setToolTipText("Recarregar");
        buttonSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSearch1.setMaximumSize(new java.awt.Dimension(36, 36));
        buttonSearch1.setMinimumSize(new java.awt.Dimension(36, 36));
        buttonSearch1.setPreferredSize(new java.awt.Dimension(36, 36));
        buttonSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(labelNumberOfSearchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboFilter)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelNumberOfSearchResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        Utils.searchItemsOnTable(tableRegistereds, comboFilter.getSelectedItem().toString(), fieldSearch.getText().trim().toUpperCase());

        if (fieldSearch.getText().trim().equals("")) {
            labelNumberOfSearchResults.setText("");
            return;
        }

        int rowCount = tableRegistereds.getRowCount();

        if (rowCount <= 0) {
            JOptionPane.showMessageDialog(null, "Nenhum resultado para a pesquisa.", "SEM RESULTADOS!", JOptionPane.ERROR_MESSAGE);
        }

        labelNumberOfSearchResults.setText("Número de resultados encontrados: " + rowCount);

    }//GEN-LAST:event_buttonSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        utils.Utils.loadItemsOnTable(tableRegistereds);
    }//GEN-LAST:event_formWindowOpened

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int selectedRow = tableRegistereds.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um item da lista!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(
                null,
                String.format("Deseja prosseguir com o apagamento de %s ?", tableRegistereds.getValueAt(selectedRow, 1).toString()),
                "Confirmação",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            final int id = Integer.parseInt(tableRegistereds.getValueAt(selectedRow, 0).toString());
            MenuScreen.getRegisteredItems().removeIf(item -> item.getId() == id);
        } else {
            return;
        }

        utils.Utils.loadItemsOnTable(tableRegistereds);

    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFilterActionPerformed

    private void buttonSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearch1ActionPerformed

        fieldSearch.setText("");

        Utils.searchItemsOnTable(tableRegistereds, comboFilter.getSelectedItem().toString(), fieldSearch.getText().trim().toUpperCase());

        labelNumberOfSearchResults.setText("Tabela recarregada.");

    }//GEN-LAST:event_buttonSearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StockScreen dialog = new StockScreen(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonSearch1;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumberOfSearchResults;
    private javax.swing.JTable tableRegistereds;
    // End of variables declaration//GEN-END:variables
}
